$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: cnn-mellin
image: mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.3-cudnn8-ubuntu20.04
conda_file: ../../conf/python/environment-core.yaml