name: cnn-mellin
channels:
  - sdrobert
  - conda-forge
  - pytorch
  - defaults
  - local
dependencies:
  - mysql-connector-python
  - optuna=2.6.0
  - pip
  - pydrobert-mellin=0.0.0
  - pydrobert-param=0.3.0
  - pydrobert-speech=0.2.0
  - python=3.9
  - pytorch=1.8.0
  - tqdm=4.60.0
  - pip: # FIXME(sdrobert): Update to conda dep when pydrobert-pytorch releases >0.3.0
    - "git+https://github.com/sdrobert/pydrobert-pytorch.git@0e3e9741439602c6246bd4b0d22893d89425b0f2"