name: cnn-mellin
channels:
  - sdrobert
  - conda-forge
  - pytorch
  - defaults
  - local
dependencies:
  - optuna=2.6.0
  - python=3.9
  - pytorch=1.8.0
  - pydrobert-speech=0.2.0
  - pydrobert-param=0.3.0
  - pydrobert-mellin=0.0.0
  - pip
  - pip: # FIXME(sdrobert): Update to conda dep when pydrobert-pytorch releases >0.3.0
    - "git+https://github.com/sdrobert/pydrobert-pytorch.git@df218d5358d53b3ee8daaf7a824e44205ae296ac"
  - tqdm=4.60.0
