name: cnn-mellin
channels:
  - sdrobert
  - conda-forge
  - pytorch
  - defaults
  - local
dependencies:
  - optuna=2.10.0
  - pip
  - pydrobert-mellin=0.0.0
  - pydrobert-param=0.3.0
  - pydrobert-speech=0.2.0
  - python=3.9
  - pytorch=1.9.0
  - tqdm
  - scikit-learn
  - postgresql
  - pg8000
  - pip: # FIXME(sdrobert): Update to conda dep when pydrobert-pytorch releases >0.3.0
    - "git+https://github.com/sdrobert/pydrobert-pytorch.git@7abad0dbb2e80b4267aebcee492aa9fd7d83ea3f"
