name: cnn-mellin
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cmake=3.23.2
  - optuna=2.10.0
  - optuna-dashboard
  - pip
  - python=3.8
  - cudatoolkit=11.1.1
  - pytorch=1.10.2
  - tqdm
  - scikit-learn
  - postgresql
  - psycopg2
  - pytest
  - ninja
  - setuptools_scm
  - pip:
    - pydrobert-param==0.3.0
    - "git+https://github.com/sdrobert/pydrobert-speech.git@fd0c48d9db0e4ff189f37d6f655dcac6070c70dd"
    - "git+https://github.com/sdrobert/pydrobert-pytorch.git@7abad0dbb2e80b4267aebcee492aa9fd7d83ea3f"
