name: cnn-mellin
channels:
  - pytorch
  - conda-forge
dependencies:
  - pip
  - python=3.8
  - cudatoolkit=11.3.*
  - pytorch=1.10.*
  - tqdm
  - scikit-learn
  - ninja
  - pip:
    - pydrobert-param==0.3.0
    - "git+https://github.com/sdrobert/pydrobert-speech.git@fd0c48d9db0e4ff189f37d6f655dcac6070c70dd"
    - "git+https://github.com/sdrobert/pydrobert-pytorch.git@7abad0dbb2e80b4267aebcee492aa9fd7d83ea3f"
