name: cnn-mellin
channels:
  - pytorch
  - conda-forge
dependencies:
  - cmake=3.23.2
  - optuna=2.10.0
  - optuna-dashboard
  - pip
  - python=3.8
  - cudatoolkit=11.3.*
  - pytorch=1.10.*
  - tqdm
  - scikit-learn
  - postgresql
  - psycopg2
  - pytest
  - ninja
  - setuptools_scm
  - sqlalchemy<2.0
  - jiwer
  - pip:
    - azureml-core
    - pydrobert-param==0.4.1
    - "git+https://github.com/sdrobert/pydrobert-speech.git@fd0c48d9db0e4ff189f37d6f655dcac6070c70dd"
    - "git+https://github.com/sdrobert/pydrobert-pytorch.git@588b8a0c2045b813fc2a546298dd66769bd8ff14"
