$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
#enter name for your environment
name: cnn-mellin
#image to be used
image: mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.1-cudnn8-ubuntu18.04
conda_file: ../../environment.yaml
version: 1